### ISSUE TITLE
Implementation of shear formulas EN1992-1-1 and prEN1992-1-1

### ISSUE THREAD

**Issue by slobbeat** [fib-international/structuralcodes#12]
This will be done by my colleague Gijs Eumelen.

**Comment by slobbeat** [comment]
This will be done by my colleague Gijs Eumelen.

**Comment by mortenengen** [comment]
Very good! Please feel free to submit a draft PR 😃

**Comment by mortenengen** [comment]
Progress is tracked in #49.
