### ISSUE TITLE
Improve documentation for sign criteria

### ISSUE THREAD

**Issue by DanielGMorenaFhecor** [fib-international/structuralcodes#137]
A common sign criterion in a cross-section assumes the z-axis is downward, as is the case with some commercial software. 

By default, the `calculate_bending_strength` method from the `GenericSectionCalculator` class returns a negative value for theta=0, corresponding with My_min, and a positive value for theta=π/2, corresponding to My_max.  

Improved documentation would clarify this behavior. See Point 5 in [this file](https://github.com/fib-international/structuralcodes/blob/a48150c72c59b20f3fa8d481ee5191e1b3cdf67e/Issues.ipynb) developed by @MestreCarlos  for further explanation.

**Comment by talledodiego** [comment]
Thanks! you are right, For sure the documentation must be clear on these assumptions.
Here we used a CRS that is X outwards the screen, Y to the right and Z upwards. 
The signs returned are coherent with this CRS.

**Comment by mortenengen** [comment]
Issues related to theory reference in docs are collected in #185.
