### ISSUE TITLE
My-Mz calculation discrepancies for N=0 in cross section

### ISSUE THREAD

**Issue by DanielGMorenaFhecor** [fib-international/structuralcodes#141]
When validating the cross-section calculations for the My-Mz diagram, discrepancies were found when computing the diagram for axial load N=0 compared to established software.  

Please refer to Point 9 in [this notebook](https://github.com/fib-international/structuralcodes/blob/a48150c72c59b20f3fa8d481ee5191e1b3cdf67e/Issues.ipynb) developed by @MestreCarlos for more details and illustrations.

**Comment by talledodiego** [comment]
To me it seems to work as expected.

You can see here a test comparing with a standard software used in Italy.

```
# imports
from math import pi
from shapely import Polygon
import numpy as np
import matplotlib.pyplot as plt
from structuralcodes.materials.concrete import ConcreteEC2_2004
from structuralcodes.materials.reinforcement import ReinforcementEC2_2004
from structuralcodes.geometry import SurfaceGeometry
from structuralcodes.sections import add_reinforcement_line, GenericSection

# Materials
concrete = ConcreteEC2_2004(25)
reinforcemnet = ReinforcementEC2_2004(fyk=500, Es=200000, density=7850, ftk=550, epsuk=0.07)  
reinforcemnet.constitutive_law = 'elasticperfectlyplastic'
# Create section
poly = Polygon(((0, 0), (350, 0), (350, 500), (0, 500)))
geo = SurfaceGeometry(poly, concrete)
geo = add_reinforcement_line(geo, (50, 450), (300, 450), 20, reinforcemnet, n=6)
geo = add_reinforcement_line(geo, (50, 50), (300, 50), 12, reinforcemnet, n=3)
# Without axial force this is actually not needed, but I am doing anyway
geo = geo.translate(-175, -250)
sec = GenericSection(geo)
# sec = GenericSection(geo, integrator='fiber', mesh_size=0.0001)

sec.geometry
```
![image](https://github.com/user-attachments/assets/b4001552-42f4-4255-83a7-2a8e59e76038)

Domain for N = 0:

```
res = sec.section_calculator.calculate_mm_interaction_domain()
plt.plot(res.m_y*1e-6, res.m_z*1e-6, label='structuralcodes')
plt.grid()
plt.xlabel('My [kNm]')
plt.ylabel('Mz [kNm]')
plt.plot(-my_mz_vcaslu[:,0], my_mz_vcaslu[:,1], '--o', markersize=2, lw=0.5, label='VCA-slu')
plt.legend()
plt.title('N = 0 kN')
```
![image](https://github.com/user-attachments/assets/b53c1f56-bc02-4c87-9c98-430624f0af67)

Domain for N = -500 kN:

```
res = sec.section_calculator.calculate_mm_interaction_domain(n=-500e3)
plt.plot(res.m_y*1e-6, res.m_z*1e-6, label='structuralcodes')
plt.grid()
plt.xlabel('My [kNm]')
plt.ylabel('Mz [kNm]')
plt.plot(-my_mz_vcaslu[:,0], my_mz_vcaslu[:,1], '--o', markersize=2, lw=0.5, label='VCA-slu')
plt.legend()
plt.title('N = -500 kN')
```

![image](https://github.com/user-attachments/assets/83bb70a3-5514-4ca8-81bf-5310f0987e64)

Probably, as the case before the apparent difference is for having the coordinate 0,0 not at the baricenter of concrete section as I mentioned in #140. It is intended to include also N * e in computation of M when there is an eccentricity between baricenter of concrete and (0,0). See also following comparison from Italian software Vcaslu:

![Comparison VCA SLU point applciation N](https://github.com/user-attachments/assets/e1ff984c-1bfd-4015-9546-c1a2b42e77b4)

**Comment by mortenengen** [comment]
Is this issue solved by translating the section to the origin?
