### ISSUE TITLE
Create milestones for the project

### ISSUE THREAD

**Issue by mortenengen** [fib-international/structuralcodes#22]
Edited June 2nd, 2023

We plan to track the progress of the project using milestones. What should these milestones be?

We suggest to use milestones for grouping issues and pull requests in related topics.

We suggest to adopt continuous integration, providing fast releases, so linking milestones to releases is perhaps not necessary. However, milestone # 0 is related to the framework of the package, and upon completion could mark the initial stable release, 0.0.1. We suggest that further releases, that should be incremental upon merging PRs, should follow [semantic versioning](http://semver.org).

We suggest that the milestone numbering could indicate the timeline, but not necessarily indicate consequentiality, i.e. milestone # 3 does not require milestone # 1 and # 2 to be completed, however, milestone # 2 requires # 1 to be completed, since # 2 is related to integrating # 1 in the package framework.

## # 0 Framework → 0.0.1

- Naming conventions: recommended rules that need to be followed in naming classes and functions in the public namespace.
- Material classes: MC2010 Concrete, EC2 Concrete, MC2010 Reinforcement, EC2 Reinforcement
- Section classes: Rectangular reinforced concrete, generic reinforced concrete section
- Structural element classes: column, straight beam
- Framework for documentation
- Documentation for material, section and structural element classes

## # 1a EC2 2023: Properties and property development

- Property development: strengths, stiffnesses, creep, shrinkage, etc.
- Constitutive relations
- Design strengths

## # 1b EC2 2023: Ultimate limit state

- Stress distribution for ULS
- Transverse shear ULS
- Torsion ULS
- Punching ULS
- Combined actions ULS: bending, axial, shear
- Slender members
- Prestressing losses

## # 1c EC2 2023: Serviceability limit state

- Crack width calculations
- Minimum reinforcement
- Deflection calculations

## # 1d EC2 2023: strut and tie and detailing

- Reinforcement detailing
- Strut and tie modelling

## # 1e EC2 2023: Fatigue

- Fatigue

## # 1f EC2 2023: Misc

- Durability?

## # 2a Integrate EC2 2023 in the framework

- Material classes
- Section classes? Depends on how this is implemented in #0.
- Structural element classes? Depends on how this is implemented in #0.

## # 3 MC2020
...

## # 4 Integrate MC2020 in the framework
...

etc. for EC2 2004 and MC2010

**Comment by sshaave** [comment]
Hi. As a new member on this project I would like to see some text explaining the vision and motivaion for this work, what the aim currently is, and how we envision this program/code to be used for the end user (are we doing only one calculation or several millions when we run the program).

**Comment by mortenengen** [comment]
Thanks for the comment, @slobbeat. We have updated the initial comment above based on your input 😃

**Comment by mortenengen** [comment]
I have created milestones related to the package framework, and also Eurocode 2 2023 based on a brief review by @talledodiego and myself. We should do the same for fib Model Code 2020.

- [ ] Review fib Model Code 2020 and create related milestones.

**Comment by DanielGMorenaFhecor** [comment]
Here is my draft for the milestones for the package framework related to MC2020.
As the MC2020 is extensive, we may need to add more sections in the future under demand.

@aperezcaldentey and @MestreCarlos , feel free to add or remove chapters if you consider it necessary.

_* Next to all bullet points, I have written the respective chapter as of the last Draft of the Model Code 2020._ 

## 3a MC2020: Material properties (14 – 16)
- Concretes (14): compressive strength (14.6.1.1), tensile stress (14.6.1.2), modulus of elasticity (14.6.1.4), stress-strain relations (14.6.1.5), time effects (14.6.1.6) and temperature effects (14.6.1.7).
- Reinforcing steel (15): stress-strain relations and strength (15.10.1, 15.10.2).
- Prestressing steel (16): stress-strain relations and strength (16.1.5.3, 16.1.9.2).

## 3b MC2020: Ultimate Limit State (30.1)

- Bending with and without axial force (30.1.2)
- Shear (30.1.3)
- Torsion with and without axial force and/or bending (30.1.4)
- Punching (30.1.5)
- Strut-and-tie models (30.1.6)
- Compression members (30.1.7)
- Fatigue (30.2.2)

## 3c MC2020: Serviceability Limit State (30.5)

- Limit state of cracking (30.5.2.4)
- Limit state of deformation (30.5.2.5)

**Comment by mortenengen** [comment]
I have updated the milestones according to your comment @DanielGMorenaFhecor.
