### ISSUE TITLE
chore: group tests in sub-packages according to design code or scope

### ISSUE THREAD

**Issue by mortenengen** [fib-international/structuralcodes#81]
The test suite is starting to grow, and is expected to continue to do so, and it would be good to group the tests in sub-packages to enhance maintainability.

As a start, we could re-organize the tests folder as follows:

```
tests/
| -- test_core
|    | ... put all tests related to core functionality here
| -- test_mc2010
|    | ... put all tests related to mc2010 here
| ... etc.
```

Each subfolder should also include an empty `__init__.py` file.

**Comment by alllexxx1** [comment]
I would take this issue if no one minds

**Comment by alllexxx1** [comment]
@mortenengen, am I right that all 3 currently existing tests relate to mc2010? If so, should I create 'test_core' folder with no tests inside?

**Comment by mortenengen** [comment]
> @mortenengen, am I right that all 3 currently existing tests relate to mc2010? If so, should I create 'test_core' folder with no tests inside?

Hi @alllexxx1 😃  on main, there are only three test scripts as you mention, `test_concrete_mc2010.py` and `test_mc2010_material_properties.py` are related to mc2010, and the last is related to core. However, it would be great if you could start form the tip of the dev branch where we have accumulated more tests 👍

**Comment by alllexxx1** [comment]
@mortenengen,got it! Thank you for answer
